#ifndef _UTF8_EXTRA_H_INCLUDE_
#define _UTF8_EXTRA_H_INCLUDE_

#include <tgb/stdextra.h>

#define UTF8_BOX_CONNECT_NONE	0x00
#define UTF8_BOX_CONNECT_RIGHT	0x10
#define UTF8_BOX_CONNECT_LEFT	0x20
#define UTF8_BOX_CONNECT_TOP	0x40
#define UTF8_BOX_CONNECT_BOTTOM	0x80

#define UTF8_BOX_HORIZONTAL 		           0
#define UTF8_BOX_HORIZONTAL_INTERSECTION_DOWN  1
#define UTF8_BOX_HORIZONTAL_INTERSECTION_UP    2
#define UTF8_BOX_VERTICAL					   3
#define UTF8_BOX_VERTICAL_INTERSECTION_RIGHT   4
#define UTF8_BOX_VERTICAL_INTERSECTION_LEFT    5
#define UTF8_BOX_CORNER_TOP_LEFT			   6
#define UTF8_BOX_CORNER_TOP_RIGHT			   7
#define UTF8_BOX_INTERSECTION				   8
#define UTF8_BOX_CORNER_BOTTOM_LEFT			   9
#define UTF8_BOX_CORNER_BOTTOM_RIGHT		   10

#define UTF8_BOXSTYLE_LIGHT					0
#define UTF8_BOXSTYLE_HEAVY					1
#define UTF8_BOXSTYLE_LIGHT_DOUBLE_DASH		2
#define UTF8_BOXSTYLE_HEAVY_DOUBLE_DASH		3
#define UTF8_BOXSTYLE_LIGHT_TRIPLE_DASH		4
#define UTF8_BOXSTYLE_HEAVY_TRIPLE_DASH		5
#define UTF8_BOXSTYLE_LIGHT_QUADRUPLE_DASH	6
#define UTF8_BOXSTYLE_HEAVY_QUADRUPLE_DASH	7
#define UTF8_BOXSTYLE_DOUBLE				8
#define UTF8_BOXSTYLE_ROUND					9
#define UTF8_BOXSTYLE_USER					10

#define UTF8_PROGRESSBAR_0		0
#define UTF8_PROGRESSBAR_12_5	1
#define UTF8_PROGRESSBAR_25		2
#define UTF8_PROGRESSBAR_37_5	3
#define UTF8_PROGRESSBAR_50		4
#define UTF8_PROGRESSBAR_62_5	6
#define UTF8_PROGRESSBAR_75		7
#define UTF8_PROGRESSBAR_87_5	8
#define UTF8_PROGRESSBAR_100	9

#define UTF8_PROGRESSBARSTYLE_BOTTOM_TOP 0
#define UTF8_PROGRESSBARSTYLE_LEFT_RIGHT 1
#define UTF8_PROGRESSBARSTYLE_USER		 2

#define UTF8_ARROW_RIGHT	0
#define UTF8_ARROW_DOWN		1
#define UTF8_ARROW_LEFT		2
#define UTF8_ARROW_UP		3

#define UTF8_ARROW_TRIANGLE				0
#define UTF8_ARROW_TRIANGLE_FILL		1
#define UTF8_ARROW_SMALL_TRIANGLE		2
#define UTF8_ARROW_SMALL_TRIANGLE_FILL	3
#define UTF8_ARROW_NORMAL				4
#define UTF8_ARROW_NORMAL_FILL			5
#define UTF8_ARROW_TWOHEADED			6
#define UTF8_ARROW_CONNECTED			7
#define UTF8_ARROW_HARPOON_UP			8
#define UTF8_ARROW_HARPOON_DOWN			9
#define UTF8_ARROW_PAIRED				10
#define UTF8_ARROW_DOUBLE				11
#define UTF8_ARROW_TIP					12
#define UTF8_ARROW_HOOK					13
#define UTF8_ARROW_RELOAD				14
#define UTF8_ARROW_DOUBLETIP			15
#define UTF8_ARROW_SPECIAL				16
#define UTF8_ARROW_USER					17

#endif

